spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: library
  security:
    user:
      password: password
  mvc:
    log-request-details: true
  application:
    name: libraryapp
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
      embedding:
        model: qwen3-embedding:0.6b
    vectorstore:
      mongodb:
        initialize-schema: false
        collection-name: books_embedded
        index-name: vector_index
        path-name: embedding

server:
  port: 5400

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          mongodb: DEBUG
jwt:
  secret: mySuperSecretKeyWithEnoughLength!